"""
Utility modules for the AFIRGen backend system.

This package provides reusable utilities for common operations:
- validators: Input validation and sanitization
- constants: Shared constants and enums
- common: Common utility functions
- field_filter: Field filtering for API responses
- pagination: Pagination utilities

Requirements: 8.5
"""

from .validators import (
    ValidationError,
    sanitize_text,
    validate_text_length,
    validate_uuid,
    validate_fir_number,
    validate_alphanumeric,
    validate_file_extension,
    validate_mime_type,
    validate_file_size,
    validate_positive_integer,
    validate_non_negative_integer,
    validate_range,
    validate_enum_value,
    validate_json_depth,
    validate_email,
    validate_url,
)

from .constants import (
    TextLimits,
    FileLimits,
    AllowedFileTypes,
    RegexPatterns,
    HTTPStatus,
    RetryDefaults,
    CircuitBreakerDefaults,
    CacheTTL,
    PaginationDefaults,
    CompressionDefaults,
    TaskPriority,
    TaskDefaults,
    AlertThresholds,
    MetricsDefaults,
    DatabaseDefaults,
    ValidationStep,
    TaskStatus,
    CircuitState,
    LogLevel,
    ErrorCode,
    SensitiveFields,
    CircuitBreakerNames,
    ContentType,
    HeaderNames,
)

from .common import (
    truncate_string,
    normalize_whitespace,
    to_snake_case,
    to_camel_case,
    mask_sensitive_data,
    get_current_timestamp,
    format_timestamp,
    parse_timestamp,
    timestamp_to_iso,
    iso_to_timestamp,
    generate_hash,
    generate_md5,
    generate_sha256,
    encode_base64,
    decode_base64,
    generate_uuid,
    generate_correlation_id,
    generate_fir_number,
    deep_merge,
    flatten_dict,
    chunk_list,
    remove_none_values,
    get_nested_value,
    set_nested_value,
    safe_json_loads,
    safe_json_dumps,
    pretty_json,
    retry_on_exception,
    safe_compare,
    is_empty,
    to_bool,
    to_int,
    to_float,
)

from .field_filter import FieldFilter
from .pagination import (
    CursorInfo,
    PaginatedResponse,
    PaginationHandler,
)

__all__ = [
    # Validators
    "ValidationError",
    "sanitize_text",
    "validate_text_length",
    "validate_uuid",
    "validate_fir_number",
    "validate_alphanumeric",
    "validate_file_extension",
    "validate_mime_type",
    "validate_file_size",
    "validate_positive_integer",
    "validate_non_negative_integer",
    "validate_range",
    "validate_enum_value",
    "validate_json_depth",
    "validate_email",
    "validate_url",
    # Constants
    "TextLimits",
    "FileLimits",
    "AllowedFileTypes",
    "RegexPatterns",
    "HTTPStatus",
    "RetryDefaults",
    "CircuitBreakerDefaults",
    "CacheTTL",
    "PaginationDefaults",
    "CompressionDefaults",
    "TaskPriority",
    "TaskDefaults",
    "AlertThresholds",
    "MetricsDefaults",
    "DatabaseDefaults",
    "ValidationStep",
    "TaskStatus",
    "CircuitState",
    "LogLevel",
    "ErrorCode",
    "SensitiveFields",
    "CircuitBreakerNames",
    "ContentType",
    "HeaderNames",
    # Common utilities
    "truncate_string",
    "normalize_whitespace",
    "to_snake_case",
    "to_camel_case",
    "mask_sensitive_data",
    "get_current_timestamp",
    "format_timestamp",
    "parse_timestamp",
    "timestamp_to_iso",
    "iso_to_timestamp",
    "generate_hash",
    "generate_md5",
    "generate_sha256",
    "encode_base64",
    "decode_base64",
    "generate_uuid",
    "generate_correlation_id",
    "generate_fir_number",
    "deep_merge",
    "flatten_dict",
    "chunk_list",
    "remove_none_values",
    "get_nested_value",
    "set_nested_value",
    "safe_json_loads",
    "safe_json_dumps",
    "pretty_json",
    "retry_on_exception",
    "safe_compare",
    "is_empty",
    "to_bool",
    "to_int",
    "to_float",
    # Field filter
    "FieldFilter",
    # Pagination
    "CursorInfo",
    "PaginatedResponse",
    "PaginationHandler",
]
