/**
 * Print Handler Module
 * Handles print functionality for FIR documents
 */

class PrintHandler {
  constructor() {
    this.init();
  }

  init() {
    this.setupPrintButtons();
    this.setupPrintStyles();
  }

  /**
   * Setup print buttons
   */
  setupPrintButtons() {
    // Find all print buttons
    const printButtons = document.querySelectorAll('[data-action="print"], .print-btn, #print-btn');
    
    printButtons.forEach(button => {
      button.addEventListener('click', (e) => {
        e.preventDefault();
        this.handlePrint();
      });
    });
  }

  /**
   * Setup print styles
   */
  setupPrintStyles() {
    // Ensure print.css is loaded
    if (!document.querySelector('link[href*="print.css"]')) {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = 'css/print.css';
      link.media = 'print';
      document.head.appendChild(link);
    }
  }

  /**
   * Handle print action
   */
  handlePrint() {
    // Prepare document for printing
    this.preparePrintDocument();
    
    // Trigger print dialog
    window.print();
    
    // Cleanup after print
    this.cleanupPrintDocument();
  }

  /**
   * Prepare document for printing
   */
  preparePrintDocument() {
    // Add print-mode class to body
    document.body.classList.add('print-mode');
    
    // Add print header if not exists
    this.addPrintHeader();
    
    // Add print footer if not exists
    this.addPrintFooter();
    
    // Hide non-printable elements
    this.hideNonPrintableElements();
  }

  /**
   * Add print header
   */
  addPrintHeader() {
    if (document.querySelector('.print-header')) {
      return;
    }

    const header = document.createElement('div');
    header.className = 'print-header print-only';
    header.innerHTML = `
      <h1>AFIRGen - FIR Document</h1>
      <div class="print-date">Printed on: ${new Date().toLocaleString()}</div>
    `;
    
    const mainContent = document.querySelector('.main-content') || document.body;
    mainContent.insertBefore(header, mainContent.firstChild);
  }

  /**
   * Add print footer
   */
  addPrintFooter() {
    if (document.querySelector('.print-footer')) {
      return;
    }

    const footer = document.createElement('div');
    footer.className = 'print-footer print-only';
    footer.innerHTML = `
      <p>Generated by AFIRGen - AI-powered FIR Management System</p>
      <p>© ${new Date().getFullYear()} AFIRGen. All rights reserved.</p>
    `;
    
    const mainContent = document.querySelector('.main-content') || document.body;
    mainContent.appendChild(footer);
  }

  /**
   * Hide non-printable elements
   */
  hideNonPrintableElements() {
    const nonPrintable = document.querySelectorAll('[data-no-print]');
    nonPrintable.forEach(element => {
      element.style.display = 'none';
    });
  }

  /**
   * Cleanup after printing
   */
  cleanupPrintDocument() {
    // Use afterprint event if available
    if ('onafterprint' in window) {
      window.addEventListener('afterprint', () => {
        this.performCleanup();
      }, { once: true });
    } else {
      // Fallback: cleanup after a delay
      setTimeout(() => {
        this.performCleanup();
      }, 1000);
    }
  }

  /**
   * Perform cleanup
   */
  performCleanup() {
    // Remove print-mode class
    document.body.classList.remove('print-mode');
    
    // Show hidden elements
    const nonPrintable = document.querySelectorAll('[data-no-print]');
    nonPrintable.forEach(element => {
      element.style.display = '';
    });
  }

  /**
   * Print specific element
   */
  printElement(element) {
    if (!element) {
      console.error('Element not found for printing');
      return;
    }

    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    
    if (!printWindow) {
      console.error('Could not open print window');
      return;
    }

    // Get all stylesheets
    const styles = Array.from(document.styleSheets)
      .map(sheet => {
        try {
          return Array.from(sheet.cssRules)
            .map(rule => rule.cssText)
            .join('\n');
        } catch (e) {
          return '';
        }
      })
      .join('\n');

    // Build print document
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Print - AFIRGen</title>
        <style>${styles}</style>
        <link rel="stylesheet" href="css/print.css" media="print">
      </head>
      <body>
        <div class="print-header">
          <h1>AFIRGen - FIR Document</h1>
          <div class="print-date">Printed on: ${new Date().toLocaleString()}</div>
        </div>
        ${element.innerHTML}
        <div class="print-footer">
          <p>Generated by AFIRGen - AI-powered FIR Management System</p>
          <p>© ${new Date().getFullYear()} AFIRGen. All rights reserved.</p>
        </div>
      </body>
      </html>
    `);

    printWindow.document.close();
    
    // Wait for content to load, then print
    printWindow.onload = () => {
      printWindow.print();
      printWindow.close();
    };
  }

  /**
   * Print FIR modal content
   */
  printFIRModal() {
    const modalContent = document.querySelector('#success-content');
    if (modalContent) {
      this.printElement(modalContent);
    } else {
      console.error('FIR modal content not found');
    }
  }
}

// Initialize on DOM ready
if (typeof window !== 'undefined') {
  window.PrintHandler = PrintHandler;
  
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
      window.printHandler = new PrintHandler();
    });
  } else {
    window.printHandler = new PrintHandler();
  }
}

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = PrintHandler;
}
